ALTER TABLE companies
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS primary_color VARCHAR(7) DEFAULT '#FF6A00',
ADD COLUMN IF NOT EXISTS secondary_color VARCHAR(7) DEFAULT '#0A2342',
ADD COLUMN IF NOT EXISTS tagline VARCHAR(255);