ALTER TABLE attendances ADD COLUMN IF NOT EXISTS employee_id UUID REFERENCES employees(id);
ALTER TABLE attendances ADD COLUMN IF NOT EXISTS hours_worked DECIMAL(5,2);
ALTER TABLE attendances ADD COLUMN IF NOT EXISTS latitude DECIMAL(10,7);
ALTER TABLE attendances ADD COLUMN IF NOT EXISTS longitude DECIMAL(10,7);
ALTER TABLE attendances ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'PRESENT';